### ISSUE TITLE
Missing api for User Activity Feed (aka checkins)

### ISSUE THREAD

**Issue by kriben** [mdlayher/untappd#1]
Hi!

Great api! I have been playing a bit with it, but could not find a way to list checkins for a given user which is documented here: https://untappd.com/api/docs#useractivityfeed

My suggestion would be to add two new methods to the User api:

``` go
Checkins(username string) ([]*Checkin, *http.Response, error)
CheckinsMinMaxId(username string, minId int, maxId int, sort Sort) ([]*Checkin, *http.Response, error)
```

Where the checkin struct looks something like this:

``` go
type Checkin struct {
    // Metadata from Untappd.
    ID          int
    Beer *Beer
    Created time.Time
    Comment string
    UserRating float64
}
```

Regards Kristian

**Comment by mdlayher** [comment]
Hi there!  Glad you've found this client useful.  I'd like to implement all of the unauthenticated API endpoints (then work on the authenticated ones), but I've been pretty busy recently.

Thanks for the PR!  I don't have time to review it immediately, but I should be able to take a look later tonight or tomorrow!  Thanks again for reaching out.

**Comment by mdlayher** [comment]
I've merged your PR, but did some manual cleanup on the documentation, and to remove the unneeded `rawCheckinBeer` type, since `rawBeer` already covered all of the fields.  Thanks!
